### ISSUE TITLE
LMES03B-20 | Visualización de mapas de amigos

### ISSUE THREAD

**Issue by uo276026** [Arquisoft/lomap_es3b#96]
# Descripción  
Obtención y visualización de los mapas de tus amigos

# Elementos modificados
- MapsPage.tsx
- FriendsPods.ts
- Friends.ts
- Markers.ts

**Comment by UO271588** [comment]
Por culpa de inrupt actualmente los mapas se tienen que incluir en el área publica puesto que al añadir o quitar un ACL en Inrupt aparece como que tienes permisos pero en realidad al acceder a la carpeta no te deja. Esto se ha comentado con el profesor correspondiente de laboratorio (Irene) y se ha llegado a la conclusión de dejarlo en la carpeta pública aunque eso conlleve el que cualquier persona pueda acceder a nuestro mapa.
